services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"


  frontend:
    build:
      context: ./React-Portfolio
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
