# Default Spring Profile
server:
  error:
    include-message: always

logging:
  level:
    root: INFO
    com.library: DEBUG
    org.springframework.data.mongodb.core.MongoTemplate: TRACE

---

# for docker

spring:
  config:
    activate:
      on-profile: docker

  data:
    mongodb:
      username: user
      password: pwd
      host: mongodb
      port: 27017
      database: portfolio-db
      authentication-database: admin
      auto-index-creation: true

server:
  port: 8080

  error:
    include-message: always

logging:
  level:
    root: INFO
    com.nneji: DEBUG

frontend:
  url: http://localhost:3000

backend:
  url: http://localhost:8080

website:
  domain: localhost