name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: computer_alerts-fe/package-lock.json
    - name: Install dependencies
      run: npm install
      working-directory: ./computer_alerts-fe
    - name: Run npm lint to ensure frontend code is linted
      run: npm run lint
      working-directory: ./computer_alerts-fe
    - name: Run build to ensure no build errors and ignore minor warnings
      run: |
        CI=false npm run build || true
      working-directory: ./computer_alerts-fe
